name: Maria Aslanidou
title: Data Scientist | Astrophysicist
email: mariaasla391@gmail.com
description: >-
  Physicist turned data scientist. Experienced in Python, machine learning, and satellite data analysis. Passionate about solving real-world problems through data.
url: "https://mariaasla.github.io"
baseurl: "" # VERY IMPORTANT – do not remove quotes

markdown: kramdown
highlighter: rouge
theme: minima
